---
# tasks file for ansible-role-kodi


# ----- Setup -----
- name: "Setup | apt | ensure Kodi repository present"
  sudo: Yes
  apt_repository: repo={{ kodi_pkg_apt_repo }}


- name: "Setup | apt | ensure Kodi base packages present"
  sudo: Yes
  apt: name={{ item }} update_cache=yes cache_valid_time=86400
  with_items:
  - software-properties-common
  - "kodi={{ kodi_pkg_apt_ver }}*"


- name: "Setup | apt | ensure Kodi pvr package present"
  sudo: Yes
  apt: name={{ kodi_pkg_pvr }} update_cache=yes cache_valid_time=86400
  when: kodi_pkg_pvr is defined


# ----- Config -----
- name: "Config| all | ensure Kodi conf folders"
  file: path={{ item }} state=directory owner={{ ansible_ssh_user }} mode=0755
  with_items:
  - "~/.kodi/"
  - "~/.kodi/userdata"


- name: "Config| all | ensure sources.xml templated"
  template: src=sources.xml.j2 dest="~/.kodi/userdata/sources.xml" owner={{ ansible_ssh_user }} mode=0755


- name: "Config| all | ensure advancedsettings.xml templated"
  template: src=advancedsettings.xml.j2 dest="~/.kodi/userdata/advancedsettings.xml" owner={{ ansible_ssh_user }} mode=0755


...